### ISSUE TITLE
Re-voting for Formal specification and analysis of Attestation in Confidential Computing

### ISSUE THREAD

**Issue by muhammad-usama-sardar** [CCC-Attestation/governance#10]
# Background material
Previous relevant Attestation SIG presentations:

| Date | Track | Presentation | Presenter | Materials |
| --- | --- | --- | --- | --- |
| 2023-02-14 | Proposal | Transparency and Interoperability for Attestation in Confidential Computing | Muhammad Usama Sardar (@muhammad-usama-sardar) | <ul><li>[slides](https://www.researchgate.net/publication/368543950_Transparency_and_Interoperability_for_Attestation_in_Confidential_Computing)</li><li>[paper](https://www.researchgate.net/publication/367284929_SoK_Attestation_in_Confidential_Computing)</li></ul> |
| 2022-10-11 | Information & data models for attestation | Preliminary proposal: Addressing 3 Key Problems of Attestation in Confidential Computing | Muhammad Usama Sardar (@muhammad-usama-sardar) | <ul><li>[paper](https://www.researchgate.net/publication/367284929_SoK_Attestation_in_Confidential_Computing)</li></ul> |
| 2022-05-24 | Information & data models for attestation | Intel TDX | Muhammad Usama Sardar (@muhammad-usama-sardar) | <ul><li>[slides](https://www.researchgate.net/publication/360861674_Presentation_Formats_for_Attestation_in_Intel_TDX)</li><li>[paper](https://www.researchgate.net/publication/351699567_Demystifying_Attestation_in_Intel_Trust_Domain_Extensions_via_Formal_Verification)</li></ul> |
| 2022-03-29 | secure channel establishment | Formal analysis of Enclave Key Exchange Protocol (EKEP) | Tom Roeder (@tmroeder) | <ul><li>[ProVerif model](https://github.com/google/ekep-analysis)</li><li>[protocol spec](https://asylo.dev/docs/concepts/ekep.html)</li></ul> |

Relevant IETF/IRTF discussions:

- [Proposed Formal Methods RG](https://csperkins.org/research/protocol-standards/2022-11-30-usable-formal-methods/)
- [some discussions at mailing list](https://mailarchive.ietf.org/arch/browse/irtf-discuss/)

# Proposal
Formal specification and analysis of all phases of attestation mechanisms in Confidential Computing using [ProVerif](https://ieeexplore.ieee.org/document/9833653) for the following TEEs:

1. Intel TDX
2. Arm CCA
3. AMD SEV-SNP 

The deliverables for each of the above TEEs are as follows:

- formal specification and analysis of initialization and attestation protocol phases in Proverif
- formal specification and analysis of provisioning phase in ProVerif

# Proponents
Muhammad Usama Sardar (@muhammad-usama-sardar)

**Comment by muhammad-usama-sardar** [comment]
Summary of public vote of chairs: 
@thomas-fossati vote: https://github.com/CCC-Attestation/governance/issues/9#issuecomment-1472365248
@KeithMoyer vote: https://github.com/CCC-Attestation/governance/issues/9#issuecomment-1474113493
@gkostal vote: https://github.com/CCC-Attestation/governance/issues/9#issuecomment-1476230860
@shnwc: we wait for your vote. 
@MikeCamel: The last time he was seen in the SIG is 18th Jan, 2022!

**Comment by MikeCamel** [comment]
I resigned from the co-chairmanship soon after. No idea why this wasn't recorded.

On 3 April 2023 18:39:01 BST, Muhammad Usama Sardar ***@***.***> wrote:
>Summary of public vote of chairs: 
>@thomas-fossati vote:
>https://github.com/CCC-Attestation/governance/issues/9#issuecomment-1472365248
>@KeithMoyer vote:
>https://github.com/CCC-Attestation/governance/issues/9#issuecomment-1474113493
>@gkostal vote:
>https://github.com/CCC-Attestation/governance/issues/9#issuecomment-1476230860
>@shnwc: we wait for your vote. 
>@MikeCamel: The last time he was seen in the SIG is 18th Jan, 2022!
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/CCC-Attestation/governance/issues/10#issuecomment-1494722026
>You are receiving this because you were mentioned.
>
>Message ID:
>***@***.***>

-Mike.

**Comment by dcmiddle** [comment]
Thanks for recreating the issue so we can assess from a clean slate.
The co-chairs will initiate a vote once they have had a chance to review and discuss.

**Comment by muhammad-usama-sardar** [comment]
> Thanks for recreating the issue so we can assess from a clean slate. The co-chairs will initiate a vote once they have had a chance to review and discuss.

It has already been sufficiently discussed for several months in SIG meetings as well as in #9.

**Comment by dcmiddle** [comment]
Roll call vote taken at 2023/04/11 meeting.
@thomas-fossati @shnwc @gkostal voted yes.
@KeithMoyer absent, but sent a yes over email to the other co-chairs.

The repo was already created, so I don't think there is anything to do.
@muhammad-usama-sardar  please just double check that the final version of the scope is reflected in the repo.
