### ISSUE TITLE
Proposal to create an Interoperable RA-TLS Project

### ISSUE THREAD

**Issue by shnwc** [CCC-Attestation/governance#8]
Proposal to create an Interoperable RA-TLS Project
====

# Background

Based on the recent CCC Attestation SIG presentation on [Interoperable RA-TLS](https://github.com/CCC-Attestation/meetings/blob/main/materials/ShanweiCen_Interoperable_ATLS.pdf) and recommendations, we have created documents with detailed X.509 cert extension and evidence formats definition. Pull requests have been created in existing RA-TLS projects (Gramine, RATS-TLS, Open Enclave, SGX SDK) add support of the proposed scheme.

# Proposal

This proposal is to create a project (interoperable-ra-tls) under the CCC Attestation SIG, to host design documents and interoperability tests.

The [Interoperable RA-TLS](https://github.com/CCC-Attestation/meetings/blob/main/materials/ShanweiCen_Interoperable_ATLS.pdf) presentation forms initial version of the proposed scheme, which will be further clarified and refined in the design documents to be hosted in this projects. Though the presentation mentioned about IANA registration, the proposed scheme will not put restrictions on which registry must be used. Different evidence formats could be suitable for different registries.

# Proponents

- Shanwei Cen (@shnwc)
- Dan Middleton (@dcmiddle)

**Comment by KeithMoyer** [comment]
I support creation of this project with a scope of encouraging commonality between existing/future RA-TLS implementations through documentation and conformance tests. If the scope is to expand in the future to include implementation code for other projects to rely upon, further discussion/approval should occur.

**Comment by shnwc** [comment]
@KeithMoyer Thank you for your support! Yes the scope is to encourage interoperability between existing/future RA-TLS implementations through documentation and conformance tests.

@thomas-fossati The tagged CBOR data is the same as the "CMW CBOR Tags" format defined in [draft-ftbs-rats-msg-wrap](https://datatracker.ietf.org/doc/draft-ftbs-rats-msg-wrap/), which supports tags registered with CoAP as well as other registries. The RA-TLS proposal does not put limitations as to which registry must be used. Different evidence formats could be suitable for different registries.

[draft-ietf-lamps-key-attestation-ext](https://datatracker.ietf.org/doc/draft-ietf-lamps-key-attestation-ext/) focuses on certificate management protocols extension and WebAuthn. The RA-TLS scope is different, it uses an X.509 cert extended with and OID containing evidence that covers the subject public key. The DICE OIDs aligns perfectly.

**Comment by thomas-fossati** [comment]
> @thomas-fossati The tagged CBOR data is the same as the "CMW CBOR Tags" format defined in [draft-ftbs-rats-msg-wrap](https://datatracker.ietf.org/doc/draft-ftbs-rats-msg-wrap/), which supports tags registered with CoAP as well as other registries. The RA-TLS proposal does not put limitations as to which registry must be used. Different evidence formats could be suitable for different registries.

Maybe make this point clearer in the description.

> [draft-ietf-lamps-key-attestation-ext](https://datatracker.ietf.org/doc/draft-ietf-lamps-key-attestation-ext/) focuses on certificate management protocols extension and WebAuthn. The RA-TLS scope is different, it uses an X.509 cert extended with and OID containing evidence that covers the subject public key. The DICE OIDs aligns perfectly.

I think it's worth for you and @nedmsmith to have a chat with Carl Wallace on this point.  I've spoken to him last week and he said he was happy to make room to CMWs in the LAMPS extension.  I can organise a meet-up if you are interested.

**Comment by nedmsmith** [comment]
Yes. Please arrange a meeting.

**Comment by shnwc** [comment]
In response to "Maybe make this point clearer in the description", clarification will be in the design document to be posted in this new project, and reviews and updates can be done there. The project proposal in this issue should avoid trying to define the solution itself.

**Comment by thomas-fossati** [comment]
> In response to "Maybe make this point clearer in the description", clarification will be in the design document to be posted in this new project, and reviews and updates can be done there. The project proposal in this issue should avoid trying to define the solution itself.

That's exactly the issue I have tried to highlight with the document linked above: it looks to already define the solution.

My thinking is that there is potentially a way to tweak the design to profit from a stronger harmonisation with other parts of the ecosystem, not just between the RA-TLS solutions.

**Comment by dcmiddle** [comment]
In our spirit of minimum viable governance, I would like to unblock this RA-TLS harmonization.
A valuable first goal is getting these 3 CCC projects interoperable. That's actually a really big outcome for our SIG. 
As we do that if we can improve from that to a broader goal that's great, but I would prefer we not block the creation of this repo while sorting that out.

**Comment by thomas-fossati** [comment]
> @thomas-fossati please see updated description with the clarification. Let me know if that addressed your concern.

awesome, thanks.

**Comment by shnwc** [comment]
Thank you @thomas-fossati! Since there is no objection from other chairs, I'll move forward to create the repo.

**Comment by shnwc** [comment]
The project repo has been created, this issue is now closed.

**Comment by dcmiddle** [comment]
The new repo for reference: 
https://github.com/CCC-Attestation/interoperable-ra-tls
